python main.py \
  --run_name "test_react_simulate" \
  --root_dir "exp" \
  --dataset_path ./benchmarks/verilogeval-simulate-hard.jsonl \
  --task "react_fix_simulate" \
  --agent_feedback "rag" \
  --language "verilog" \
  --model "gpt-3.5-turbo-16k-0613" \
  --pass_at_k "1" \
  --max_iters "15" \
  --max_budgets "30" \
  --num_samples '5' \
  --verbose
